version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend # Указывает на папку с Dockerfile для фронтенда
    ports:
      - "3000:3000" # Прокидываем порт фронтенда
    depends_on:
      - backend # Зависимость от бэкенда (если нужно)

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jzkzkqtm
      POSTGRES_USER: jzkzkqtm
      POSTGRES_PASSWORD: vINhxaXLfiRC3ILoao6xDXpFLvG7bYMn

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/uploads:/usr/share/nginx/html/uploads
